baseURL = ""
languageCode = "en-us"
title = "Metaphor"


[params]
dateFormat = "Jan 2, 2006"
type = "website"
brandimage = "/img/qulture_logo.svg"
footertext = "powered by Hugo & Tachyons"
footertextsub = "©metaphor"

[menu]


[taxonomies]
tag = "tags"
category = "categories"