baseURL = ""
languageCode = "en-us"
title = "Qulture Collective"


[params]
dateFormat = "Jan 2, 2006"
type = "website"
footertext = "powered by Hugo & Tachyons"
footertextsub = "© Qulture Collective"

[menu]
  [[menu.main]]
    name = "home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Blog"
    url = "/blog"
    weight = 2
  [[menu.main]]
    name = "Contact"
    url = "/contact"
    weight = 3

  [taxonomies]
  tag = "tags"
  category = "categories"